# Generated by Django 5.1.4 on 2025-01-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('admin', 'Admin'), ('doctor', 'Shifokor'), ('registrator', 'Registrator'), ('other', 'Boshqa hodim')], default='other', help_text="Role bo'lishi mumkin: 'ceo', 'admin', 'doctor', 'registrator' 'other'", max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', help_text="Status bo'lishi mumkin: 'active', 'inactive'", max_length=30),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
