# Generated by Django 5.1.4 on 2025-01-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_address_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Foydalanuvchi ', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
