# Generated by Django 5.1.4 on 2025-01-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_room_for_patient'),
        ('users', '0006_remove_user_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stuff.room'),
        ),
    ]
