# Generated by Django 5.1.4 on 2025-01-04 14:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': "Bo'lim ",
                'verbose_name_plural': "Bo'limlar ",
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('room', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('all_seats', models.IntegerField(default=1)),
                ('free_seats', models.IntegerField()),
                ('seat_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stuff.section')),
            ],
            options={
                'verbose_name': 'Xona ',
                'verbose_name_plural': 'Xonalar ',
            },
        ),
    ]
