# Generated by Django 5.1.4 on 2025-01-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at'], 'verbose_name': 'Xona ', 'verbose_name_plural': 'Xonalar '},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-created_at'], 'verbose_name': "Bo'lim ", 'verbose_name_plural': "Bo'limlar "},
        ),
    ]
