# Generated by Django 5.1.4 on 2025-01-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='for_patient',
            field=models.BooleanField(default=True),
        ),
    ]
