# Generated by Django 5.1.4 on 2025-01-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientservice',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
