# Generated by Django 5.1.4 on 2025-01-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patientservice_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mijoz ', 'verbose_name_plural': 'Mijozlar '},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bemor ', 'verbose_name_plural': 'Bemorlar'},
        ),
        migrations.AlterModelOptions(
            name='patientservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bemor xizmat ', 'verbose_name_plural': 'Bemor xizmatlari '},
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10),
        ),
        migrations.CreateModel(
            name='PatientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.TextField(blank=True, null=True)),
                ('summa', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'verbose_name': "Bemor to'lov ",
                'verbose_name_plural': "Bemor to'lovlar ",
                'ordering': ['-created_at'],
            },
        ),
    ]
