# Generated by Django 5.1.4 on 2025-01-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_turn_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turn',
            options={'ordering': ['-appointment_time'], 'verbose_name': 'Navbat', 'verbose_name_plural': 'Navbatlar'},
        ),
    ]
