# Generated by Django 5.1.4 on 2025-01-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_turn_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turn',
            options={'verbose_name': 'Navbat', 'verbose_name_plural': 'Navbatlar'},
        ),
    ]
