# Generated by Django 5.1.4 on 2025-01-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_turn_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turn',
            options={'ordering': ['-appointment_time', 'turn_num'], 'verbose_name': 'Navbat', 'verbose_name_plural': 'Navbatlar'},
        ),
    ]
