# Generated by Django 5.1.4 on 2025-01-23 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_turn_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientservice',
            name='turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.turn'),
        ),
        migrations.AddField(
            model_name='turn',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
